FROM        node:8-alpine
MAINTAINER  Milan Simonovic <milan.simonovic@imls.uzh.ch>

ADD . /scripts/

WORKDIR /scripts

RUN npm install

# neo4j username & pass should come thru ENV
ENV NEO4J_PASS neo4j

CMD ["node", "bin/index"]
