FROM        meringlab/node6
MAINTAINER  Milan Simonovic <milan.simonovic@imls.uzh.ch>

ADD . /scripts/

CWD /scripts

RUN npm install

# neo4j username & pass should come thru ENV
ENV CONSUL_HOST tethys.meringlab.org
ENV NEO4J_PASS seeecret

CMD ["node", "bin/index"]
